### PR TITLE
[BREAKING] delete should return boolean, set should throw TypeError

### PR DESCRIPTION
**Pull request by jasonmit**
* updated deps
* `delete` returns boolean based on spec https://tc39.github.io/ecma262/#sec-weakmap.prototype.delete
* `set` should throw `TypeError` https://tc39.github.io/ecma262/#sec-weakmap.prototype.set
* `import Weakmap from 'ember-weakmap';`
  * if native `WeakMap` is available it will use that otherwise export the polyfill

Should be version as a breaking change.

### CODE REVIEW

**Comment by stefanpenner** [comment]
:+1:

**Comment by thoov** [comment]
:balloon:

**Comment by stefanpenner** [comment]
looks like the private one in ember has also fixed this: https://github.com/emberjs/ember.js/commit/bce8ed35161f8d830375a8ccd4cd3dd8c0e1d4bf

**Pull request merged**
