### PR TITLE
Add missing "debug" dependency

### PR DESCRIPTION
**Pull request by Turbo87**
/cc @thoov

### CODE REVIEW

**Comment by thoov** [comment]
Thanks @Turbo87

**Comment by Turbo87** [comment]
wow, that was fast! :)

**Comment by Turbo87** [comment]
any chance for a quick `3.0.1` release? I saw you bumped the version already, but it isn't showing up at https://yarnpkg.com/en/package/ember-weakmap yet 🤔

**Comment by thoov** [comment]
@Turbo87 3.0.1 Just published

**Pull request merged**
